version: '3.8'

services:
  telegram_bot:
    build: .
    volumes:
      - ./samples:/app/samples
    container_name: telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: always
